### ISSUE TITLE
怎么批量导入微信表情包呀？

### ISSUE THREAD

**Issue by HackerGBD** [zhaoolee/ChineseBQB#125]
想导入微信，发现只能一个一个的导。

**Comment by zhaoolee** [comment]
推荐直接使用配套的小程序,选择表情包后,转发即可 
![](https://www.v2fy.com/asset/0i/ChineseBQB/chinesebqb-md/000readme-chinesebqb.assets/61185261-cce80980-a689-11e9-9f5e-2774faba3339.png)
如果实在想保存,将转发出的表情包长按保存为表情包即可
(微信有表情包数量限制,不推荐批量导入~)

**Comment by zhaoolee** [comment]
> 想导入微信，发现只能一个一个的导。

使用这款更方便的表情包关键词搜索工具吧
https://www.v2fy.com/asset/0i/ChineseBQB/
