### ISSUE TITLE
表情包名称问题

### ISSUE THREAD

**Issue by yueyue10** [zhaoolee/ChineseBQB#126]
表情包的【类目】有了，但是每个表情包没有对应的【名称】只有编号

场景：想要搜索特定表情包的话就没有办法了。
感觉【类目】的表情包只适合浏览，不适合使用啊。

**Comment by zhaoolee** [comment]
确实可以加名称，就是工作量有点大，需要群众的力量！

**Comment by zhaoolee** [comment]
> 表情包的【类目】有了，但是每个表情包没有对应的【名称】只有编号
> 
> 场景：想要搜索特定表情包的话就没有办法了。
> 感觉【类目】的表情包只适合浏览，不适合使用啊。

搞定了！
