### ISSUE TITLE
cdn/icon?family=Material+Icons文件名带有问号,导致windows上检出失败,能修改下文件名吗?

### ISSUE THREAD

**Issue by ShowMeBaby** [zhaoolee/ChineseBQB#138]
windows不支持文件名带有?,会检出失败

```bash
git.exe checkout master --
error: invalid path 'cdn/icon?family=Material+Icons'
```

**Comment by ggymm** [comment]
使用这个忽略错误，不影响其他文件检出

```bash
git config core.protectNTFS false
```

**Comment by GeeLaw** [comment]
这个解决方案并不令人满意——比如关闭 `core.protectNTFS` 是否会带来安全隐患？

这个文件是 [commit `5d52b04`](https://github.com/zhaoolee/ChineseBQB/commit/5d52b042959def4cfd907b26e4f218b49ebc18b7) 引入的，综合同一个 commit 的其他修改，这个文件似乎没有实质的作用——它的内容和 `MaterialIcons.css` 一样，且后者被 `index.html` 第 25 行引用。此外根据命名方式可以猜测这个文件是某种 web crawler 自动下载的，被请求的路径是 `icon`，而 `?` 和后面的内容是 query。我怀疑流行的 web server 并不会把 `./cdn/icon?family=Material+Icons` 映射为 `cdn/icon?family=Material+Icons` 这个文件，而是忽略 `?family=Material+Icons` 并映射为 `cdn/icon`。综上，该文件很可能是无意义的且妨碍 Windows 用户，如果是这样，应该删除之。

请作者 @zhaoolee 关注一下这个问题，并给出解答。

**Comment by Eadela** [comment]
赞成删除该问题文件
严重影响win用户下载
现在每个win用户都需要去关闭NTFS保护机制的配置

**Comment by zhaoolee** [comment]
> 这个解决方案并不令人满意——比如关闭 `core.protectNTFS` 是否会带来安全隐患？
> 
> 这个文件是 [commit `5d52b04`](https://github.com/zhaoolee/ChineseBQB/commit/5d52b042959def4cfd907b26e4f218b49ebc18b7) 引入的，综合同一个 commit 的其他修改，这个文件似乎没有实质的作用——它的内容和 `MaterialIcons.css` 一样，且后者被 `index.html` 第 25 行引用。此外根据命名方式可以猜测这个文件是某种 web crawler 自动下载的，被请求的路径是 `icon`，而 `?` 和后面的内容是 query。我怀疑流行的 web server 并不会把 `./cdn/icon?family=Material+Icons` 映射为 `cdn/icon?family=Material+Icons` 这个文件，而是忽略 `?family=Material+Icons` 并映射为 `cdn/icon`。综上，该文件很可能是无意义的且妨碍 Windows 用户，如果是这样，应该删除之。
> 
> 请作者 @zhaoolee 关注一下这个问题，并给出解答。

已移除问号
