### ISSUE TITLE
Github 仓库容量有限, 爆仓了作者打算怎么办 ?

### ISSUE THREAD

**Issue by Lionad-Morotar** [zhaoolee/ChineseBQB#31]

**Comment by Lionad-Morotar** [comment]
@zhaoolee

**Comment by zhaoolee** [comment]
哈哈, 其实也蛮简单的, 如果本仓库A真的爆仓了, 我会建一个新仓库B用来存储图片, 本仓库A只保留仓库B的图片链接

已经实践过的案例： 《谷粒-Chrome仓库英雄榜》https://github.com/zhaoolee/ChromeAppHeroes内所有图片, 都来自《图床》仓库 https://github.com/zhaoolee/GraphBed

**Comment by GongT** [comment]
毕竟不是干这个的，不是很好，此时需要拉赞助买S3（滑稽）

**Comment by zhaoolee** [comment]
@GongT   

嗯嗯, 刚刚在README.md里面留了一个赞赏码~

![image](https://user-images.githubusercontent.com/15868458/60851884-f3401c00-a227-11e9-8f54-b30c130d05c9.png)

**Comment by HeLiangHIT** [comment]
机智的方法

**Comment by Lionad-Morotar** [comment]
哈哈 厉害
