### ISSUE TITLE
Typos, lots of typos.

### ISSUE THREAD

**Issue by gaoryrt** [zhaoolee/ChineseBQB#32]
表情包：meme
仓库：repo
an sticker -> a sticker
贡献方法：Contribution
大佬：Dalao
给大佬点烟：light Dalao up a cig

**Comment by gaoryrt** [comment]
翻译是故意的嘛 🤣

**Comment by zhaoolee** [comment]
的确是故意的~ [手动滑稽]

**Comment by gaoryrt** [comment]
oooookay
