### ISSUE TITLE
chrome 右键复制gif大家有方案么？

### ISSUE THREAD

**Issue by xwsg** [zhaoolee/ChineseBQB#40]
右键复制的表情只有一帧，变成了非动图

**Comment by zhaoolee** [comment]
拖拽上传即可, 看gif图中我的操作~

![fun](https://user-images.githubusercontent.com/15868458/61108999-5f37b400-a4b6-11e9-9cd3-4e0d51813646.gif)

**Comment by xwsg** [comment]
@zhaoolee 感谢回复，这样是可以实现，不过还是稍微有点繁琐，没有右键复制图片快捷😀，
测试了一下微信（windows版）可以拖拽，TIM （windows版）

**Comment by zhaoolee** [comment]
微信网页版拖拽保存表情图片，挺不错的
