### ISSUE TITLE
开源小程序

### ISSUE THREAD

**Issue by F-loat** [zhaoolee/ChineseBQB#41]
使用 [Taro](https://github.com/NervJS/taro) 框架开发了一个[小程序](https://github.com/F-loat/ChineseBQB-client)，获取 markdown 文件后解析来展示本仓库的内容，便于浏览表情包并发送给好友。

<p style="vertical-align: center">
  <img alt="首页" src="https://raw.githubusercontent.com/F-loat/ChineseBQB-client/master/screenshots/index.jpg" width="32%" />
  <img alt="关于" src="https://raw.githubusercontent.com/F-loat/ChineseBQB-client/master/screenshots/about.jpg" width="32%" />
  <img alt="列表" src="https://raw.githubusercontent.com/F-loat/ChineseBQB-client/master/screenshots/list.jpg" width="32%" />
</p>

**Comment by zhaoolee** [comment]
好棒! 审核通过了,我把它写到README文档里面[手动滑稽~]

**Comment by F-loat** [comment]
![gh_9336f669d08a_258](https://user-images.githubusercontent.com/16759376/61169490-ccb81300-a590-11e9-8c09-adf1d23240a8.jpg)

审核通过了，还挺顺利😎

**Comment by zhaoolee** [comment]
哈哈, 好棒! 我把这个加上~ 
![image](https://user-images.githubusercontent.com/15868458/61170673-58d13700-a59f-11e9-9a85-48b871dd4260.png)

**Comment by F-loat** [comment]
可以的，近期我继续优化下，有什么建议也可以提给我
