### ISSUE TITLE
这个不是柯基🐶吗（滑稽

### ISSUE THREAD

**Issue by LewisTian** [zhaoolee/ChineseBQB#44]
强行 Cat 哈哈哈哈哈哈

![TIM20190715150453](https://user-images.githubusercontent.com/23132915/61199850-07958480-a712-11e9-90f2-64b0524ae318.png)

**Comment by zhaoolee** [comment]
已将柯基移入狗窝~

![image](https://user-images.githubusercontent.com/15868458/61259297-247e9600-a7ac-11e9-8bfb-693588c142bc.png)
