### ISSUE TITLE
表情加载是有点慢的

### ISSUE THREAD

**Issue by peterzhanghui** [zhaoolee/ChineseBQB#53]
建议对图片优化一下。
小程序还是很好用的。

**Comment by F-loat** [comment]
这个可能可以在代理服务器上做些缓存处理，我最近配置看看，GitHub 的资源国内部分网络访问确实会比较慢

**Comment by F-loat** [comment]
下一版小程序内的图片资源改用了 gitcdn.link，理论上速度会快一点，今晚应该就会发布

**Comment by F-loat** [comment]
<div>
  <img alt="github" src="https://raw.githubusercontent.com/zhaoolee/ChineseBQB/master/002CuteGirl_可爱的女孩纸👧BQB/CuteGirl00006.gif" />
  <img alt="gitcdn" src="https://gitcdn.link/repo/zhaoolee/ChineseBQB/master/002CuteGirl_可爱的女孩纸👧BQB/CuteGirl00006.gif" />
  <img alt="proxy" src="https://proxy.youngon.com.cn/github/raw/zhaoolee/ChineseBQB/master/002CuteGirl_可爱的女孩纸👧BQB/CuteGirl00006.gif" />
</div>

1. github 👍

2. gitcdn 😄

3. proxy 🎉

看到的同学帮忙投个票？

**Comment by zhaoolee** [comment]
1

**Comment by peterzhanghui** [comment]
nginx可以考虑配置一下gzip，文件会小很多

**Comment by F-loat** [comment]
图片资源 gz 压缩效果不大的
