### ISSUE TITLE
表情包049命名错误

### ISSUE THREAD

**Issue by wfly1998** [zhaoolee/ChineseBQB#84]
关于表情包`049CuteLittleFox_可爱小狐狸BQB`命名错误的issue

该表情包出自番剧`にゃんこデイズ`，中文译名为~~两个呆子~~`猫咪日常`，国内为b站独家播送。其中名场面“给我也整一个”出自《猫咪日常》第7集。

综上所述，该表情包所描述内容为~~猫娘~~可爱小猫咪，并非狐狸。

证毕。

**Comment by F-loat** [comment]
是猫尾巴没chuo了

**Comment by zhaoolee** [comment]
已解决,感谢提醒~
![image](https://user-images.githubusercontent.com/15868458/62291488-a4884980-b496-11e9-8af4-c39ce3a394ec.png)
