### ISSUE TITLE
表情商店

### ISSUE THREAD

**Issue by kangyu0414** [zhaoolee/ChineseBQB#89]
要是能够在微信表情商店里直接能够搜索到，然后直接添加到自己表情包里，这样是不是就更加方便了呢。。。。 比如说可以按照胖虎系列、假笑系列等来分类。

**Comment by iostalks** [comment]
微信搜索小程序"豆笔表情"，有这个仓库的表情，转发到聊天窗口，即可收藏。

欢迎试用~

**Comment by seanM29** [comment]
> 微信搜索小程序"豆笔表情"，有这个仓库的表情，转发到聊天窗口，即可收藏。
> 
> 欢迎试用~

小程序打开以后 图片加载不出来，都是白色的 @iostalks

**Comment by iostalks** [comment]
> > 微信搜索小程序"豆笔表情"，有这个仓库的表情，转发到聊天窗口，即可收藏。
> > 欢迎试用~
> 
> 小程序打开以后 图片加载不出来，都是白色的 @iostalks

因为图片在 Github 上，加载会比较慢，稍微等一会儿会出来的，加载完可以把喜欢的表情收藏一下。
