### ISSUE TITLE
中国表情包 小程序版

### ISSUE THREAD

**Issue by iostalks** [zhaoolee/ChineseBQB#90]
小程序版表情包已通过，因为是 Github 的图片，加载会有些慢，请耐性等待。

![image](https://raw.githubusercontent.com/iostalks/images/master/blog/findFaceQR.jpg)

**Comment by zhaoolee** [comment]
![image](https://user-images.githubusercontent.com/15868458/62586965-78375780-b8f2-11e9-90c1-bd5e8b67b197.png)

加到项目介绍里面了~

**Comment by focusxia** [comment]
小程序表情包加载不出来

**Comment by iostalks** [comment]
> 小程序表情包加载不出来

加载速度受网络环境影响哦~
