### ISSUE TITLE
请求帮忙寻找添加《今天也要开心“鸭”！》这类表情包！

### ISSUE THREAD

**Issue by 54czp** [zhaoolee/ChineseBQB#98]
https://www.sohu.com/a/243349369_661138

![image](https://user-images.githubusercontent.com/17570717/70307319-d98d1a00-1843-11ea-8f9a-26ae4340f518.png)

**Comment by zhaoolee** [comment]
加了==

https://zhaoolee.com/ChineseBQB/057HappyDuck_%E5%BC%80%E5%BF%83%E9%B8%ADBQB/
